# HLS Apps Analytics Hub v2.1 - Deployment Configuration
# Using python directly (like supply-chain-app)
command: ["python", "app_enhanced.py"]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "4b28691c780d9875"

  - name: "ANALYTICS_CATALOG"
    value: "hls_amer_catalog"

  - name: "ANALYTICS_SCHEMA"
    value: "apps_telemetry"

  # Embedded Dashboard URLs - uncomment and set to enable
  # - name: "LOGFOOD_ANALYTICS_URL"
  #   value: ""

  # - name: "INFRASTRUCTURE_METRICS_URL"
  #   value: ""
